# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'QuickDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftUtils', '~> 4.0.1' # Swift shorthand.
  pod 'MVVM-Swift', '~> 1.1.0' # MVVM Architect for iOS Application.
  pod 'ObjectMapper', '3.1.0' # Simple JSON Object mapping written in Swift. Please fix this version to 2.2.6 now.
  pod 'Kingfisher', '~> 4.5.0'

  # Pods for QuickDemo

  target 'QuickDemoTests' do
      inherit! :complete
      pod 'Nimble', '7.0.2'
      pod 'Quick', '1.2.0'
  end

end
