osx_image: xcode10.2
language: objective-c
rvm:
  - 2.6.3
cache:
  - bundler
  - cocoapods
before_install:
  - gem update --system
  - gem install bundler
  - bundle install
  - bundle exec pod install
# xcode_project: UnitTestExample.xcodeproj # path to your xcodeproj folder
xcode_scheme: UnitTestExample
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 8
script: 
  - xcodebuild -workspace UnitTestExample.xcworkspace -scheme UnitTestExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
