osx_image: xcode10.2
language: swift
rvm:
  - 2.6.3
cache:
  - bundler
  - cocoapods
before_install:
  - gem update --system
  - gem install bundler
  - bundle install
  - bundle exec pod install --repo-update
  - gem install linterbot
  - brew install swiftlint
  - bundle exec fastlane deploy_dev
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 8
before_script:
  - chmod +x ./scripts/add-key.sh
  - sh ./scripts/add-key.sh
script:
  - ./scripts/lint
