osx_image: xcode10.2
language: objective-c
rvm:
  - 2.6.3
cache:
  - bundler
  - cocoapods
script:
  - xctool -workspace UnitTestExample.xcworkspace -scheme UnitTestExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
# xcode_project: UnitTestExample.xcodeproj # path to your xcodeproj folder
# xcode_scheme: UnitTestExampleTests
# xcode_destination: platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)
