osx_image: xcode10.2
language: swift
rvm:
  - 2.6.3
cache:
  - bundler
  - cocoapods
before_install:
  - gem update --system
  - gem install bundler
  - bundle install
  - bundle exec pod install --repo-update
  - gem install linterbot
  - brew install swiftlint
  - bundle exec fastlane test
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 8
script: 
  - ./scripts/lint
  - chmod +x ./scripts/add-key.sh
  - sh ./scripts/add-key.sh
  - xcodebuild -workspace UnitTestExample.xcworkspace -scheme UnitTestExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
