# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!
target 'NimbleDemo' do
    use_frameworks!

    target 'NimbleDemoTests' do
        inherit! :search_paths
        # Pods for testing
        pod 'Nimble', '7.0.2'
    end
end
