# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'OhhttpStubTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'OHHTTPStubs/Swift', '8.0.0'
  pod 'Alamofire', '4.8.2'
  pod 'ObjectMapper', '3.4.2'

  target 'OhhttpStubTutorialTests' do
    inherit! :search_paths
  end
end
