default_platform(:ios)

platform :ios do
  lane :dev do
    import_certificate(
      certificate_path: "./Cers/dev.cer",
      certificate_password: "",
      keychain_name: "abcd.keychain"
    )
    install_provisioning_profile(path: "./Cers/provisioning_app_buildapp_testing_new.mobileprovision")
    build_app(
      scheme: "Dev",
      export_method: "development",
      output_name: "UnitTestProject-Dev.ipa",
      export_options: {
        provisioningProfiles: { 
          "com.lamle.dev.buildappsetting": "provisioning_app_buildapp_testing_new"
        }
      }
    )
  end

  lane :prod do
    build_app(
      scheme: "Prod",
      export_method: "ad-hoc",
      output_name: "UnitTestProject-Prod.ipa",
      export_options: {
        provisioningProfiles: { 
          "com.lamle.dev.buildappsetting.prod": "provisioning_app_buildapp_testing_prod"
        }
      }
    )
  end
end
