lane :test do

  import_certificate(
    keychain_name: "ios-build.keychain",
    keychain_password: "12345678",
    certificate_path: "./Cers/dev.p12",
    certificate_password: "12345678"
  )

  build_app(
    scheme: "UnitTestExample",
    configuration: "Debug",
    clean: true,
    output_directory: "ipa/dev",
    output_name: "UnitTest.ipa",
    skip_profile_detection: true,
    silent: true,
    export_method: "development",
    export_options: {
      provisioningProfiles: { "com.lamle.dev.buildappsetting": "Fastlane_dev" }
    }
  )
end
